# .github/workflows/telegram-notify.yml
name: Telegram Notification

on:
  repository_dispatch:
    types: [pr_opened_event]

jobs:
  send-telegram-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ğŸ“£ æ–°çš„ PR å·²å»ºç«‹ï¼
            
            å„²å­˜åº«: ${{ github.event.client_payload.repository }}
            PR æ¨™é¡Œ: ${{ github.event.client_payload.title }}
            ä½œè€…: ${{ github.event.client_payload.sender }}
            é€£çµ: ${{ github.event.client_payload.html_url }}

